- name: Uninstall Nginx (Optional Undeploy Task)
  hosts: webservers
  become: yes
  tasks:
    - name: Stop and Remove Nginx
      systemd:
        name: nginx
        state: stopped
        enabled: no

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove website files
      file:
        path: /var/www/html/index.html
        state: absent
